# Site settings
title: Distributed Systems Reading Group
email: dsrg@csail.mit.edu
description: >
  DSRG is a Distributed Systems Reading Group at MIT. We meet once a week on
  the 9th floor of Stata to discuss distributed systems research papers, and
  cover papers from conferences like SOSP, OSDI, PODC, VLDB, and SIGMOD. We try
  to have a healthy mix of current systems papers and older seminal papers.
baseurl: "/dsrg"
url: "http://mit-pdos.github.io"

# Build settings
markdown: kramdown

exclude: ['vendor', 'Makefile', 'Gemfile.lock', 'Gemfile']

gems:
  - octopress-solarized
  - octopress-codefence
